apiVersion: v2
name: storagecheck
description: A Helm chart for check storage in Kubernetes Cluster
type: application
version: 1.0.2
appVersion: "1.0.2"
maintainers:
  - name: eumel8
    email: f.kloeker@telekom.de
    url: https://www.telekom.com
