apiVersion: v2
name: storagecheck
description: A Helm chart for check storage in Kubernetes Cluster
type: application
version: 2.0.0
appVersion: "2.0.0"
maintainers:
  - name: eumel8
    email: f.kloeker@telekom.de
    url: https://www.telekom.com
