replicaCount: 1

image:
  repository: ghcr.io/eumel8/storagecheck/storagecheck
  pullPolicy: Always
  #tag: dev

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# additional env,e.g. CHECK_IMAGE
#
# env:
#   - name: CHECK_IMAGE
#     value: ghcr.io/mcsps/busybox:1.0.8

podAnnotations: {}

# minimal permissions for pod
podSecurityContext:
  fsGroup: 1000
  supplementalGroups:
  - 1000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# minimal permissions for container
securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
    - CAP_NET_RAW
  privileged: false
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

# service for Monitoring
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

# resources for Container
resources:
  limits:
    memory: 250Mi
    cpu: 500m
  requests:
    memory: 64Mi
    cpu: 300m

nodeSelector: {}

tolerations: []

affinity: {}

# loglevel of application (info,error,debug)
logLevel: info

# storagecheck parameter
checkinterval: "1800"

# create a servicemonitor for Prometheus
servicemonitor:
  enabled: false

# create a Kyverno policy exception for the check pod
policyexception:
  enabled: false
