---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "storagecheck.fullname" . }}
  labels:
    {{- include "storagecheck.labels" . | nindent 4 }}
spec:
  ingress:
  - ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
    {{- include "storagecheck.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
